# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "nixpool/local/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7547-A724";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "nixpool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "nixpool/safe/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "nixpool/safe/persist";
      fsType = "zfs";
    };

  swapDevices = [ ];

}
